// AUTOGENERATED by scripts/gen-mmq-spill-table.sh -- do not hand-edit.
//
// [TAG_MMQ_SPILL_TABLE] Per-(type, mmq_x) VGPR spill counts for gfx1201,
// extracted from the compiled device ELFs (llvm-readobj --notes on the
// .hip_fatbin of each mmq-instance-*.cu.o) after a full build.
//
// WHY THIS EXISTS: the mmq_x selection loop filters candidates on SHARED MEMORY
// ONLY and never consults register pressure, so it can and does pick a tile that
// spills. Every spilling kernel below sits at vgpr_count=256, the wave32
// architectural ceiling on gfx1201 -- the compiler has already given it every
// register there is. Measured consequences of that blind spot:
//   Q2_K  @ mmq_x=80  -> 741 spills -> pp512 312 vs Q4_K 2305 (~7x), fixed once
//                        by hand (TAG_Q2_K_WMMA_MMQ_X_HISTORY) after it was
//                        found by benchmark rather than by construction.
//   Q6_K  @ mmq_x=128 -> 18 spills  -> prefill -39.6% vs Q5_K_M despite decode
//                        tracking size normally (-6.1%).
//   Q5_0/Q5_1 @ 128   -> 44/48 spills -> the unexplained prefill deficit in the
//                        2026-09-05 format matrix.
// Each was diagnosed by hand, one at a time. This table makes it a build fact.
//
// Regenerate after ANY change to mmq.cuh, the tile sizes, or the toolchain --
// spill counts are a property of the compiled code, not of the algorithm.

#pragma once

#include <stdint.h>

static constexpr struct { int type; int mmq_x; int spills; } MMQ_SPILLS[] = {
    { /* Q4_0      */   2,   32,    4 },
    { /* Q4_0      */   2,  128,   14 },
    { /* Q5_0      */   6,   96,   10 },
    { /* Q5_0      */   6,  112,   32 },
    { /* Q5_0      */   6,  128,   47 },
    { /* Q5_1      */   7,   96,   10 },
    { /* Q5_1      */   7,  112,   36 },
    { /* Q5_1      */   7,  128,   51 },
    { /* Q8_0      */   8,   32,   32 },
    { /* Q2_K      */  10,   16,   32 },
    { /* Q2_K      */  10,   32,  105 },
    { /* Q2_K      */  10,   48,  214 },
    { /* Q2_K      */  10,   64,  349 },
    { /* Q2_K      */  10,   80,  812 },
    { /* Q3_K      */  11,   16,   11 },
    { /* Q3_K      */  11,  112,    5 },
    { /* Q3_K      */  11,  128,   19 },
    { /* Q6_K      */  14,  128,   18 },
    { /* IQ2_XXS   */  16,   32,   14 },
    { /* IQ2_XXS   */  16,   48,   36 },
    { /* IQ2_XXS   */  16,   64,   42 },
    { /* IQ2_XXS   */  16,   96,    1 },
    { /* IQ2_XXS   */  16,  112,    9 },
    { /* IQ2_XXS   */  16,  128,   21 },
    { /* IQ2_XS    */  17,   32,   12 },
    { /* IQ2_XS    */  17,   48,   24 },
    { /* IQ2_XS    */  17,   96,    2 },
    { /* IQ2_XS    */  17,  112,   10 },
    { /* IQ2_XS    */  17,  128,   22 },
    { /* IQ3_XXS   */  18,   32,   19 },
    { /* IQ3_XXS   */  18,   48,   45 },
    { /* IQ3_XXS   */  18,   64,   62 },
    { /* IQ3_XXS   */  18,   80,   58 },
    { /* IQ3_S     */  21,   32,   10 },
    { /* IQ3_S     */  21,   48,   35 },
    { /* IQ3_S     */  21,   64,   43 },
    { /* IQ2_S     */  22,   32,    5 },
    { /* IQ2_S     */  22,   48,   15 },
    { /* IQ2_S     */  22,   64,   42 },
    { /* IQ2_S     */  22,   96,    2 },
    { /* IQ2_S     */  22,  112,   10 },
    { /* IQ2_S     */  22,  128,   22 },
    { /* IQ4_XS    */  23,   32,   25 },
    { /* NVFP4     */  40,   16,    1 },
    { /* Q1_0      */  41,   32,    1 },
    { /* Q2_0      */  42,   32,    3 },
    { /* Q2_0      */  42,  128,   13 },
    { /* F8E4M3    */  43,  128,   13 },
    { /* MXFP6     */  49,   80,    2 },
    { /* MXFP6     */  49,   96,   15 },
    { /* MXFP6     */  49,  112,   23 },
    { /* MXFP6     */  49,  128,   38 },
};

static constexpr int MMQ_SPILLS_N = 52;
