#!/usr/bin/env python3
"""ISA compatibility grid for AMD arches: which datapath instructions each
gfx target's assembler accepts. Method: llvm-mc mnemonic-level probe --
"invalid instruction" = absent; any operand-level complaint = present
(validated against hardware probes on gfx1201, 2026-08-16).

Outputs isa-grid.json (machine-readable, per-arch profile source) and
isa-grid.md (human table). Run anywhere with ROCm LLVM."""
import json
import subprocess
import sys

MC = sys.argv[1] if len(sys.argv) > 1 else "/opt/rocm/core-7.14/lib/llvm/bin/llvm-mc"
OUT = sys.argv[2] if len(sys.argv) > 2 else "."

ARCHES = [
    # CDNA line
    "gfx900", "gfx906", "gfx908", "gfx90a", "gfx942", "gfx950",
    # RDNA line
    "gfx1010", "gfx1030", "gfx1100", "gfx1101", "gfx1102", "gfx1103",
    "gfx1150", "gfx1151", "gfx1200", "gfx1201", "gfx1250",
]

# (label, mnemonic, dummy operand string)
INSTRS = [
    # int dot family (decode paths)
    ("dp4a i8 (iu8)",        "v_dot4_i32_iu8",            "v0, v1, v2, v3"),
    ("dp4a i8 (i8)",         "v_dot4_i32_i8",             "v0, v1, v2, v3"),
    ("dot8 iu4",             "v_dot8_i32_iu4",            "v0, v1, v2, v3"),
    ("dot8 u4",              "v_dot8_u32_u4",             "v0, v1, v2, v3"),
    ("dot8 i4",              "v_dot8_i32_i4",             "v0, v1, v2, v3"),
    ("dot2 f16",             "v_dot2_f32_f16",            "v0, v1, v2, v3"),
    ("dot2 bf16",            "v_dot2_f32_bf16",           "v0, v1, v2, v3"),
    ("dot4 fp8",             "v_dot4_f32_fp8_fp8",        "v0, v1, v2, v3"),
    ("dot4 bf8",             "v_dot4_f32_bf8_bf8",        "v0, v1, v2, v3"),
    # WMMA (RDNA matrix)
    ("wmma f16",             "v_wmma_f32_16x16x16_f16",   "v[0:7], v[8:11], v[12:15], v[0:7]"),
    ("wmma bf16",            "v_wmma_f32_16x16x16_bf16",  "v[0:7], v[8:11], v[12:15], v[0:7]"),
    ("wmma iu8",             "v_wmma_i32_16x16x16_iu8",   "v[0:7], v[8:9], v[10:11], v[0:7]"),
    ("wmma iu4 K16",         "v_wmma_i32_16x16x16_iu4",   "v[0:7], v8, v9, v[0:7]"),
    ("wmma iu4 K32",         "v_wmma_i32_16x16x32_iu4",   "v[0:7], v[8:9], v[10:11], v[0:7]"),
    ("wmma fp8",             "v_wmma_f32_16x16x16_fp8_fp8", "v[0:7], v[8:9], v[10:11], v[0:7]"),
    ("wmma bf8",             "v_wmma_f32_16x16x16_bf8_bf8", "v[0:7], v[8:9], v[10:11], v[0:7]"),
    # SWMMAC (sparse)
    ("swmmac iu8 K32",       "v_swmmac_i32_16x16x32_iu8", "v[0:7], v[8:9], v[10:13], v14"),
    ("swmmac iu4 K32",       "v_swmmac_i32_16x16x32_iu4", "v[0:7], v8, v[10:11], v14"),
    ("swmmac iu4 K64",       "v_swmmac_i32_16x16x64_iu4", "v[0:7], v[8:9], v[10:13], v14"),
    ("swmmac f16",           "v_swmmac_f32_16x16x32_f16", "v[0:7], v[8:11], v[12:19], v20"),
    ("swmmac fp8",           "v_swmmac_f32_16x16x32_fp8_fp8", "v[0:7], v[8:9], v[10:13], v14"),
    # MFMA (CDNA matrix)
    ("mfma i8 16x16x16",     "v_mfma_i32_16x16x16i8",     "v[0:3], v0, v1, v[0:3]"),
    ("mfma i8 16x16x32",     "v_mfma_i32_16x16x32_i8",    "v[0:3], v[0:1], v[2:3], v[0:3]"),
    ("mfma f16 16x16x16",    "v_mfma_f32_16x16x16f16",    "v[0:3], v[0:1], v[2:3], v[0:3]"),
    ("mfma fp8 16x16x32",    "v_mfma_f32_16x16x32_fp8_fp8", "v[0:3], v[0:1], v[2:3], v[0:3]"),
    ("mfma f8f6f4 (mx)",     "v_mfma_f32_16x16x128_f8f6f4", "v[0:3], v[0:7], v[8:15], v[0:3]"),
    # cross-lane / shuffle
    ("permlanex16",          "v_permlanex16_b32",         "v0, v1, s0, s1"),
    ("permlane16",           "v_permlane16_b32",          "v0, v1, s0, s1"),
    ("byte perm",            "v_perm_b32",                "v0, v1, v2, v3"),
    ("ds bpermute",          "ds_bpermute_b32",           "v0, v1, v2"),
    ("f16 pk fma",           "v_pk_fma_f16",              "v0, v1, v2, v3"),
    ("fdot2 f16->f32",       "v_dot2_f32_f16",            "v0, v1, v2, v3"),
]

def probe(mcpu, mnem, ops):
    src = f"{mnem} {ops}\n"
    r = subprocess.run([MC, "--triple=amdgcn--amdhsa", f"--mcpu={mcpu}"],
                       input=src, capture_output=True, text=True)
    err = r.stderr
    if "invalid instruction" in err or "instruction not supported" in err:
        return False
    return True  # assembled clean OR operand-level complaint = mnemonic exists

grid = {}
for arch in ARCHES:
    row = {}
    for label, mnem, ops in INSTRS:
        row[label] = probe(arch, mnem, ops)
    grid[arch] = row
    n = sum(row.values())
    print(f"{arch}: {n}/{len(INSTRS)}")

with open(f"{OUT}/isa-grid.json", "w") as f:
    json.dump({"method": "llvm-mc mnemonic acceptance", "mc": MC,
               "instructions": [i[1] for i in INSTRS], "grid": grid}, f, indent=1)

labels = [i[0] for i in INSTRS]
with open(f"{OUT}/isa-grid.md", "w") as f:
    f.write("# AMD ISA datapath compatibility grid\n\n")
    f.write("Probe: `llvm-mc` mnemonic acceptance per `-mcpu` (operand-level errors = instruction exists; validated on gfx1201 hardware probes). Generated by `isa_grid.py`.\n\n")
    f.write("| instruction | " + " | ".join(ARCHES) + " |\n")
    f.write("|---|" + "---|" * len(ARCHES) + "\n")
    for lab in labels:
        cells = [("Y" if grid[a][lab] else "-") for a in ARCHES]
        f.write(f"| {lab} | " + " | ".join(cells) + " |\n")
print("wrote isa-grid.json / isa-grid.md")
