#!/usr/bin/env bash
# Regenerate ggml/src/ggml-cuda/mmq-spill-table.h from a BUILT tree.
#
# Spill counts are a property of the COMPILED code, so this must be re-run after
# any change to mmq.cuh, the tile sizes, the warp counts, or the toolchain. A
# stale table is worse than none: it would silently permit a tile that now spills.
#
# Usage: scripts/gen-mmq-spill-table.sh [build-dir]   (default: build-dual)
set -euo pipefail
BUILD="${1:-build-dual}"
TR="${THEROCK:-/home/jmonk/.cache/lemonade/bin/therock/gfx1201-7.13.0}"
RO="$TR/lib/llvm/bin/llvm-readobj"; OC="$TR/lib/llvm/bin/llvm-objcopy"
D="$BUILD/ggml/src/ggml-hip/CMakeFiles/ggml-hip.dir/__/ggml-cuda/template-instances"
OUT="ggml/src/ggml-cuda/mmq-spill-table.h"
[ -d "$D" ] || { echo "no template-instances in $BUILD -- build first" >&2; exit 1; }
for t in "$RO" "$OC"; do [ -x "$t" ] || { echo "missing $t" >&2; exit 1; }; done

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
n=0
for o in "$D"/mmq-instance-*.cu.o; do
  [ -f "$o" ] || continue
  "$OC" --dump-section=.hip_fatbin="$TMP/f.bin" "$o" 2>/dev/null || continue
  python3 - "$TMP" <<'PY' || continue
import sys
t=sys.argv[1]; d=open(f'{t}/f.bin','rb').read()
o=[i for i in range(len(d)-4) if d[i:i+4]==b'\x7fELF']
if o: open(f'{t}/e.elf','wb').write(d[o[0]: o[1] if len(o)>1 else len(d)])
PY
  [ -f "$TMP/e.elf" ] || continue
  "$RO" --notes "$TMP/e.elf" 2>/dev/null | python3 -c "
import sys,re
for b in re.split(r'(?=\.name:)', sys.stdin.read()):
    n=re.search(r'\.name:\s*(\S+)',b); v=re.search(r'\.vgpr_count:\s*(\d+)',b); s=re.search(r'\.vgpr_spill_count:\s*(\d+)',b)
    if not(n and v and s): continue
    m=re.search(r'mul_mat_qIL9ggml_type(\d+)ELi(\d+)E', n.group(1))
    if m and int(s.group(1))>0: print(f'{m.group(1)},{m.group(2)},{s.group(1)}')
" >> "$TMP/raw.csv" 2>/dev/null || true
  rm -f "$TMP/e.elf"; n=$((n+1))
done
[ -s "$TMP/raw.csv" ] || { echo "no spill data extracted from $n objects -- ABORTING rather than writing an empty table" >&2; exit 1; }

python3 - "$TMP/raw.csv" "$OUT" <<'PY'
import sys
src,out=sys.argv[1],sys.argv[2]
T={2:'Q4_0',3:'Q4_1',6:'Q5_0',7:'Q5_1',8:'Q8_0',10:'Q2_K',11:'Q3_K',12:'Q4_K',13:'Q5_K',14:'Q6_K',
   16:'IQ2_XXS',17:'IQ2_XS',18:'IQ3_XXS',19:'IQ1_S',20:'IQ4_NL',21:'IQ3_S',22:'IQ2_S',23:'IQ4_XS',24:'IQ1_M',
   39:'MXFP4',40:'NVFP4',41:'Q1_0',42:'Q2_0',43:'F8E4M3',44:'F8E5M2',45:'2OF4_FP8',46:'MXFP8',47:'IU4',
   48:'2OF4_F16',49:'MXFP6'}
seen={}
for l in open(src):
    try: t,x,s=[int(z) for z in l.strip().split(',')]
    except ValueError: continue
    seen[(t,x)]=max(seen.get((t,x),0),s)
rows=sorted(seen.items())
with open(out,'w') as f:
    f.write('''// AUTOGENERATED by scripts/gen-mmq-spill-table.sh -- do not hand-edit.
//
// [TAG_MMQ_SPILL_TABLE] Per-(type, mmq_x) VGPR spill counts on gfx1201, read
// from the compiled device ELFs after a full build.
//
// The mmq_x selection loop filters candidates on SHARED MEMORY only and never
// consults register pressure, so without this it can pick a spilling tile.
// Every entry sits at vgpr_count=256, the wave32 ceiling. Measured cost of that
// blind spot: Q2_K@80 = 741 spills (~7x prefill loss) and Q6_K@128 = 18 spills
// (-39.6% prefill) -- both found by benchmark and patched by hand, months apart.
//
// REGENERATE after any change to mmq.cuh, tile sizes, warp counts or toolchain.
// Spill counts describe the compiled code, not the algorithm; a stale table is
// worse than none because it permits a tile that now spills.
#pragma once

#include <stdint.h>

static constexpr struct { int type; int mmq_x; int spills; } MMQ_SPILLS[] = {
''')
    for (t,x),s in rows:
        f.write(f'    {{ /* {T.get(t,"type"+str(t)):<9} */ {t:>3}, {x:>4}, {s:>4} }},\n')
    f.write('};\n\nstatic constexpr int MMQ_SPILLS_N = %d;\n' % len(rows))
print(f"  wrote {out}: {len(rows)} spilling (type,mmq_x) pairs")
PY
